[package]
name = "minesweeper"
version = "0.1.0"
edition = "2021"

[dependencies]
leptos = { version = "0.6.15", features = ["csr", "nightly"] }
rand = "0.8.5"

[dependencies.web-sys]
version = "0.3.61"
features = [
    "TouchEvent",
    "TouchList",
    "Touch",
]

