name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

env:
  REGISTRY: "registry.digitalocean.com/runic-minesweeper"
  IMAGE_NAME: "minesweeper-app"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build container image
        run: docker build -t $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7) .

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Log in to DigitalOcean Container Registry
        run: doctl registry login --expiry-seconds 600

      - name: Push image to DigitalOcean Container Registry
        run: docker push $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        env:
          IMAGE_URL: $(echo $REGISTRY)/$(echo $IMAGE_NAME):$(echo $GITHUB_SHA | head -c7)
        with:
          host: ${{ secrets.DROPLET_HOST }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          envs: IMAGE_URL
          script: |
            docker pull $IMAGE_URL
            docker stop leptos-app || true
            docker rm leptos-app || true
            docker run -d --name leptos-app -p 80:80 $IMAGE_URL
